### ISSUE TITLE
user id is not tracking

### ISSUE THREAD

**Issue by RomanShmi** [RomanShmi/contactWebCore6#2]
- [x] User id is injected

- [x] User Id cannot be seen

**Comment by RomanShmi** [comment]
- [ ] super admin only modifying states
- [ ]  nav bar
- [ ] make sure it is clean to the user what link they on
